default: --strict --tags ~@selenium --exclude features/support/selenium.rb -r features/support -r features/step_definitions
selenium: --strict --tags @selenium -r features/support -r features/step_definitions
