default: --strict --tags ~@selenium --exclude features/support/selenium.rb --exclude features/step_definitions/selenium_steps.rb -r features/support -r features/step_definitions
selenium: --strict --tags @selenium -r features/support -r features/step_definitions
